name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish_pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build
      run: make build
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: make publish


  publish_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run e2e tests
      env:
        COMPOSE_FILE: "docker-compose.yml"
        CI_DC_DISABLE_TTY: "-T"
      run: |
        cd tests
        make e2e-run

    - name: Build and push docker image
      run: make buildx-build-n-push-image
